services:
  postgres:
    container_name: postgres-sql-hphone
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hphone
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  hphone-api:
    container_name: hphone-api
    image: firas/hphone-api:1.0.0
    environment:
      EMAIL_HOST_NAME: ${EMAIL_HOST_NAME}
      EMAIL_USER_NAME: ${EMAIL_USER_NAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "8088:8088"
    volumes:
      - phone-api-storage:/app/uploads
    networks:
      - spring-demo
    depends_on:
      - postgres

  houri-phone-ui:
    container_name: houri-phone-ui
    image: firas/houri-phone-ui:1.0.0
    ports:
      - "8080:80"
    networks:
      - spring-demo
    depends_on:
      - hphone-api
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  hphone-api-storage:
    driver: local